# Generated by Django 5.0.14 on 2026-07-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('work', 'Work Experience'), ('campus', 'Campus Organization'), ('certificate', 'Certificate')], default='work', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['category', '-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CVPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('achievement_layout', models.CharField(choices=[('nested', 'Nested under each experience'), ('section', 'Grouped in a dedicated Achievements section')], default='nested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievements', models.ManyToManyField(blank=True, related_name='presets', to='cv.achievement')),
                ('entries', models.ManyToManyField(blank=True, related_name='presets', to='cv.entry')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='cv.entry'),
        ),
    ]
